### ISSUE TITLE
What to do when bad data exists on a disbursement (and work item/defendant)

### ISSUE THREAD

**Issue by dwhenry** [ministryofjustice/laa-submit-crime-forms#107]
By default most of our forms follow a linear approach where the previous form has 
to have been completed and valid before the user can move to the next form.

However in the case of disbursements (and work item/defendant) there are a number
of ways that we can end up with an invalid disbursement, but this:

* is not visible in the summary screen
* did not block users from continuing in the flow - current code on master sends now 
them to the broken record (should have a flash message but that is broken and waiting 
on flow confirmation before being fixed)

## How can the system get into this state? 

I am going to focus on disbursements as the simple solution of remove the 'save and continue' 
button does NOT work for them!

Method:

* click 'save and continue' when bad data exists (see comment above)
* fill in the disbursement type details, get logged out of the system and not realise the 
disbursement cost details where never entered

## What is required?

* update to summary page to highlight when/if data on a record is incomplete
* guide on what should happen when user attempts to continue flow when bad data exists:
  * current approach of going to broken record (with a wokring flash message)
  * block the 'no' answer to the add another with a suitable message
  * have a message popup when the try to processed
  * have a inline error message against the broken records if they select no (re-render the summary page)
  * something else....

**Comment by patrick-laa** [comment]
I believe this is now resolved - the summary page highlights when an item is incomplete and doesn't let you proceed until you've resolved the issue with it. ("You cannot save and continue if any disbursements/work items/defendant details are incomplete")
